version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - run:
          name: Docker Build
          command: docker build -t petronetto/alpine-machine-learning-base .
      - run:
          name: Push the develop tag
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              docker tag petronetto/alpine-machine-learning-base petronetto/alpine-machine-learning-base:develop
              docker push petronetto/alpine-machine-learning-base:develop
            fi
      - run:
          name: Push the latest tag and triggerging dependencie builds
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag petronetto/alpine-machine-learning-base petronetto/alpine-machine-learning-base:latest
              docker push petronetto/alpine-machine-learning-base:latest
              curl \
                --header "Content-Type: application/json" \
                --data '{}' \
                --request POST \
                https://circleci.com/api/v1.1/project/github/petronetto/pytorch-alpine/tree/master?circle-token=$PYTORCH_ALPINE_TOKEN
            fi
      - run:
          name: Backup tag
          command: |
            docker tag petronetto/alpine-machine-learning-base petronetto/alpine-machine-learning-base:v-$CIRCLE_BUILD_NUM
            docker push petronetto/alpine-machine-learning-base:v-$CIRCLE_BUILD_NUM
